### ISSUE TITLE
Add SSH config

### ISSUE THREAD

**Issue by Thorsten-Sick** [jekil/hardentheworld#1]
https://stribika.github.io/2015/01/04/secure-secure-shell.html

Has a good explanation. Just no TL;DR for what to do

**Comment by jekil** [comment]
Thanks, i already appointed it in my todo. The point is i have a really long SSH notes i need to put in RST format and publish. Will do and stop slacking ;)

Thanks so much for the contribution.

**Comment by Thorsten-Sick** [comment]
Thanks for the project. I think it will be awesome soon. I will keep watching an try to contribute some more. Have a similar project in mind. Maybe I will just contribute to yours instead

**Comment by jekil** [comment]
Merged in the documentation
